version: '3.9'
services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: "http://nestjs:3001"
        NEXT_PUBLIC_API_SECRET: "ngDmUKoPG8KpO/09KPIaKPM+NTdzAsgGp0Z/GYkf5UIjwiwdCjcq8Gs8L2XbXGun+FrD4pCBpJQje4WjtMaLjw=="
        PORT: 3002
    ports:
      - 3002:3002
    networks:
      - shared-network

networks:
  shared-network:
    external: true